### PR TITLE
UI Rework Fix

### LINKED ISSUE #41: UI Rework Fix

### PR DESCRIPTION
**Pull request by kgeewhan**
This pull request makes it so that the side panels (both stats and settings panel) will close once you begin the timer. It also makes the stats and settings buttons accessible again once the timer has been reset.

### CODE REVIEW

File: source/scripts/timer.js [hunk 1]
```diff
@@ -159,6 +161,16 @@ export function togglePomoBreak (onBreak) {
  * @returns {Array} An array containing the pomoState and the pomoCount
  */
 export function startTimer (localOnBreak = onBreak, localPomoCount = pomoCount) {
+  // if Settings page is open close
```
Comment (friidryce) [inline source/scripts/timer.js:164]: maybe comment on reason for closing could help future devs understand why

**Review by friidryce — APPROVED** [review]
Good work! Please add some comments on the specific fix of this PR when you can (in the description).

**Review by jinbest17 — APPROVED** [review]
Great work on fixing the UI
